import tkinter as tk
def press(num):
    current = equation.get()
    equation.set(current + str(num))
def equalpress():
    try:
        result = str(eval(equation.get()))  # Evaluate the expression
        equation.set(result)
    except:
        equation.set("Error")
def clear():
    equation.set("")
root = tk.Tk()
root.title("Basic Calculator")
equation = tk.StringVar()
entry = tk.Entry(root, textvariable=equation, font=('Arial', 20), bd=10, width=15)
entry.grid(row=0, column=0, columnspan=4)
button_1 = tk.Button(root, text='1', command=lambda: press(1), width=5, height=2)
button_1.grid(row=1, column=0)
button_2 = tk.Button(root, text='2', command=lambda: press(2), width=5, height=2)
button_2.grid(row=1, column=1)
button_3 = tk.Button(root, text='3', command=lambda: press(3), width=5, height=2)
button_3.grid(row=1, column=2)
button_4 = tk.Button(root, text='4', command=lambda: press(4), width=5, height=2)
button_4.grid(row=2, column=0)
button_5 = tk.Button(root, text='5', command=lambda: press(5), width=5, height=2)
button_5.grid(row=2, column=1)
button_6 = tk.Button(root, text='6', command=lambda: press(6), width=5, height=2)
button_6.grid(row=2, column=2)
button_7 = tk.Button(root, text='7', command=lambda: press(7), width=5, height=2)
button_7.grid(row=3, column=0)
button_8 = tk.Button(root, text='8', command=lambda: press(8), width=5, height=2)
button_8.grid(row=3, column=1)
button_9 = tk.Button(root, text='9', command=lambda: press(9), width=5, height=2)
button_9.grid(row=3, column=2)
button_0 = tk.Button(root, text='0', command=lambda: press(0), width=5, height=2)
button_0.grid(row=4, column=1)
plus = tk.Button(root, text='+', command=lambda: press('+'), width=5, height=2)
plus.grid(row=1, column=3)
minus = tk.Button(root, text='-', command=lambda: press('-'), width=5, height=2)
minus.grid(row=2, column=3)
multiply = tk.Button(root, text='*', command=lambda: press('*'), width=5, height=2)
multiply.grid(row=3, column=3)
divide = tk.Button(root, text='/', command=lambda: press('/'), width=5, height=2)
divide.grid(row=4, column=3)
equal = tk.Button(root, text='=', command=equalpress, width=5, height=2)
equal.grid(row=4, column=2)
clear = tk.Button(root, text='C', command=clear, width=5, height=2)
clear.grid(row=4, column=0)
root.mainloop()
